# Generated by Django 6.0.4 on 2026-05-06 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
