# Generated by Django 6.0.4 on 2026-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_course_duration_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
