# Generated by Django 6.0.4 on 2026-05-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0002_reminderlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderlog',
            old_name='last_remainder_sent_at',
            new_name='last_reminder_sent_at',
        ),
    ]
