# Generated by Django 6.0.4 on 2026-05-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_rename_last_remainder_sent_at_reminderlog_last_reminder_sent_at'),
        ('courses', '0005_course_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assesments.assignment'),
        ),
    ]
