# Generated by Django 6.0.4 on 2026-05-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sponsored_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('act', 'Active'), ('com', 'Complete'), ('can', 'Cancelled'), ('ina', 'Inactive')], default='act', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sponsorships', to='courses.course')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sponsorships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sponsored_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('act', 'Active'), ('com', 'Complete'), ('can', 'Cancelled'), ('ina', 'Inactive')], default='ina', max_length=3)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='courses.enrollment')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sponsor', 'enrollment')},
            },
        ),
    ]
